definitions:
  models.AddRoleRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  models.CreateEmployeeRequest:
    properties:
      address:
        type: string
      birth_date:
        type: string
      birth_place:
        type: string
      email:
        type: string
      employee_number:
        type: string
      employee_type_id:
        type: string
      employment_status_id:
        type: string
      end_date:
        type: string
      full_name:
        type: string
      gender:
        type: string
      identify_card_number:
        type: integer
      join_date:
        type: string
      marital_status:
        type: string
      phone:
        type: string
      religion:
        type: string
    required:
    - address
    - birth_date
    - birth_place
    - email
    - employee_number
    - employee_type_id
    - employment_status_id
    - full_name
    - gender
    - identify_card_number
    - join_date
    - marital_status
    - phone
    - religion
    type: object
  models.CreateEmployeeTypeRequest:
    properties:
      employee_type_id:
        type: string
      employee_type_name:
        type: string
    type: object
  models.CreateEmploymentStatusRequest:
    properties:
      employment_status_id:
        type: string
      employment_status_name:
        type: string
    type: object
  models.CreateNewAccessTokenRequest:
    properties:
      refresh_token:
        type: string
    type: object
  models.Employee:
    properties:
      address:
        type: string
      birth_date:
        type: string
      birth_place:
        type: string
      created_at:
        type: string
      created_by:
        type: string
      email:
        type: string
      employee_id:
        type: string
      employee_number:
        type: string
      employee_type_id:
        type: string
      employeeType:
        $ref: '#/definitions/models.EmployeeType'
      employment_status_id:
        type: string
      employmentStatus:
        $ref: '#/definitions/models.EmploymentStatus'
      end_date:
        type: string
      full_name:
        type: string
      gender:
        type: string
      identify_card_number:
        type: integer
      is_activated:
        type: boolean
      join_date:
        type: string
      marital_status:
        type: string
      phone:
        type: string
      religion:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.EmployeeType:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      employee_type_id:
        type: string
      employee_type_name:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.EmploymentStatus:
    properties:
      created_at:
        type: string
      created_by:
        type: string
      employment_status_id:
        type: string
      employment_status_name:
        type: string
      updated_at:
        type: string
      updated_by:
        type: string
    type: object
  models.SignInRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserRegistrationRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger SIMS API Documentation
  version: "1.0"
paths:
  /api/auth/create-new-access-token:
    post:
      consumes:
      - application/json
      description: Create new access token by refresh token
      parameters:
      - description: User data
        in: body
        name: userData
        required: true
        schema:
          $ref: '#/definitions/models.CreateNewAccessTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Create new access token
      tags:
      - Authentication
  /api/auth/signin:
    post:
      consumes:
      - application/json
      description: Login with email and password
      parameters:
      - description: User data
        in: body
        name: userData
        required: true
        schema:
          $ref: '#/definitions/models.SignInRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Login as an authenticated user
      tags:
      - Authentication
  /api/employee/create:
    post:
      consumes:
      - application/json
      description: Create a new employee with join_date and end_date in format YYYY-MM-DD
      parameters:
      - description: Employee data
        in: body
        name: employeeData
        required: true
        schema:
          $ref: '#/definitions/models.CreateEmployeeRequest'
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Employee'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create employee
      tags:
      - Employee
  /api/employment/create:
    post:
      consumes:
      - application/json
      description: Create a new employee type with manual ID and name of the type
      parameters:
      - description: EmployeeType data
        in: body
        name: employeeTypeData
        required: true
        schema:
          $ref: '#/definitions/models.CreateEmployeeTypeRequest'
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Create employee type
      tags:
      - Employee Type
  /api/employment/create/employment-status:
    post:
      consumes:
      - application/json
      description: Create a new employment status with manual ID and name of the type
      parameters:
      - description: EmploymentStatus data
        in: body
        name: employmentStatusData
        required: true
        schema:
          $ref: '#/definitions/models.CreateEmploymentStatusRequest'
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Create employment status
      tags:
      - Employment Status
  /api/employment/delete/{employee_type_id}:
    delete:
      consumes:
      - application/json
      description: Delete employee type by id
      parameters:
      - description: EmployeeType ID
        in: path
        name: employee_type_id
        required: true
        type: string
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete an employee type
      tags:
      - Employee Type
  /api/employment/delete/employment-status/{employment_status_id}:
    delete:
      consumes:
      - application/json
      description: Delete employment statuses by id
      parameters:
      - description: EmploymentStatus ID
        in: path
        name: employment_status_id
        required: true
        type: string
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete an employment statuses
      tags:
      - Employment Status
  /api/employment/employee-types:
    get:
      consumes:
      - application/json
      description: Fetch all employee types
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all employee types
      tags:
      - Employee Type
  /api/employment/employment-statuses:
    get:
      consumes:
      - application/json
      description: Fetch all employment statuses
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all employment statuses
      tags:
      - Employment Status
  /api/role:
    get:
      consumes:
      - application/json
      description: Get all user roles
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get roles
      tags:
      - Roles
    post:
      consumes:
      - application/json
      description: Create new role
      parameters:
      - description: User data
        in: body
        name: userData
        required: true
        schema:
          $ref: '#/definitions/models.AddRoleRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Add Role
      tags:
      - Roles
  /api/user-service/role/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a role by role ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete a role
      tags:
      - Roles
    get:
      consumes:
      - application/json
      description: Get role by role ID
      parameters:
      - description: Role ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get a role
      tags:
      - Roles
  /api/user/:
    get:
      consumes:
      - application/json
      description: Fetch all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get all users
      tags:
      - Users
  /api/user/{id}:
    get:
      consumes:
      - application/json
      description: Fetch the user details based on the ID provided
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Get user by ID
      tags:
      - Users
  /api/user/get-user-by-email:
    get:
      consumes:
      - application/json
      description: Get user data by email
      parameters:
      - description: User email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Get user by email
      tags:
      - Users
  /api/user/profile:
    get:
      consumes:
      - application/json
      description: Fetch the user profile based on the decoded ID from access token
      parameters:
      - description: Authorization token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      summary: Get user profile
      tags:
      - Users
  /api/user/registration:
    post:
      consumes:
      - application/json
      description: Register a new user with name, email, and password
      parameters:
      - description: User data
        in: body
        name: userData
        required: true
        schema:
          $ref: '#/definitions/models.UserRegistrationRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "409":
          description: Conflict
        "500":
          description: Internal Server Error
      summary: Register a new user
      tags:
      - Users
swagger: "2.0"
